### ISSUE TITLE
JSONResultsReader not iterable when the result of the query is empty

### ISSUE THREAD

**Issue by lc4nt** [splunk/splunk-sdk-python#501] opened 2022-12-19 09:34 UTC
**Describe the bug**
When using  `oneshot`, the `JSONResultsReader` object is not iterable, if the result of the query is empty. Other type of jobs haven't been tested.

**To Reproduce**
Adjust the script below for your own environment and construct a query which doesn't return results
```
from splunklib.results import JSONResultsReader
from splunklib import client as splunkclient

from getpass import getpass

HOST = "yourhost"
PORT = 8089
USER = "youruser"

if __name__ == "__main__":
    splunkservice = splunkclient.connect(
                host=HOST,
                port=PORT,
                username=USER,
                password=getpass(),
                scheme="https",
                autologin=True)


    kwargs = {
                "latest_time": "now",
                "earliest_time": "-1h",
                "output_mode":"json",
                "f":["*"]
            }

    query = 'search index=yourindex blablabla'

    r = splunkservice.jobs.oneshot(query=query, kwargs=kwargs, output_mode='json')
    print("done with query")
    res = JSONResultsReader(r)
    print("created JSONResultsReader object")
    l = list(res)
    print("converted to list")
```

**Expected behavior**
The program ends and the variable `l` is empty

**Logs or Screenshots**
The program doesn't terminate trying to iterate over `res` indefinitely
```
(venv) [user@system]$ python oneshot.py 
Password: 
done with query
created JSONResultsReader object

```

**Splunk (please complete the following information):**
- Version: 8.1.2
- OS: RHEL

**SDK (please complete the following information):**
 - Version: 1.7.2
 - Language Runtime Version:  Python 3.9
 - OS: RHEL 8

**Comment by lc4nt** [comment] 2022-12-20 07:32
More updates and a possible workaround.  
If one tries to read the content of `ResponseReader` returned by `oneshot` by using `readall()`, the program hangs. This doesn't happen though by trying to read one byte at the time gradually expanding the buffer size:

```
    r = splunkservice.jobs.oneshot(query=query, kwargs=kwargs, output_mode='json')
    print(f"Is empty:{r.empty}")
    for i in range (1,100):
        print(f"bytes read:{i}, content {r.read(i)}")
```
The program painfully and slowly tries to read the number of bytes requested:
```
[user@system]$ python oneshot.py 
Password: 
Is empty:False
bytes read:1, content b' '
bytes read:2, content b'  '
bytes read:3, content b'   '
bytes read:4, content b'    '
bytes read:5, content b'     '
bytes read:6, content b'      '
bytes read:7, content b'       '
bytes read:8, content b'        '
bytes read:9, content b'         '
bytes read:10, content b'          '
bytes read:11, content b'           '
bytes read:12, content b'            '
bytes read:13, content b'             '
bytes read:14, content b'              '
bytes read:15, content b'               '
bytes read:16, content b'                '
bytes read:17, content b'                 '
bytes read:18, content b'                  '
bytes read:19, content b'                   '
bytes read:20, content b'                    '
bytes read:21, content b'                     '
```
What is actually the content of that buffer?
```
    r = splunkservice.jobs.oneshot(query=query, kwargs=kwargs, output_mode='json')
    print(binascii.hexlify(r.read(5)))

---------------------------------------------------------------------------
[user@system]$ python oneshot.py 
Password: 
b'2020202020'
```
**Possible workaround**
Read the first n-bytes of `ResponseReader`, if they all equal to `\x20`, the response is empty
```
    r = splunkservice.jobs.oneshot(query=query, kwargs=kwargs, output_mode='json')
    if r.read(5) == b'\x20\x20\x20\x20\x20':
        print('empty response')
        sys.exit(0)
```

**Comment by ashah-splunk** [comment] 2022-12-23 12:40
@lc4nt thank you for the details of the issue as well as for the workaround. We will look into this and provide an update soon.

**Comment by ashah-splunk** [comment] 2023-01-06 07:08
Hi @lc4nt , we were not able to reproduce the issue. The given script executed successfully in our testing without any changes in the SDK.
Please let us know if anything is missed from the script that needs to be tested.

**Comment by ashah-splunk** [comment] 2023-01-23 05:49
Closing the Issue as we haven't received any response. @lc4nt please reopen the Issue if you are still facing the issue.

**Closed by ashah-splunk** 2023-01-23 05:49 UTC
