### ISSUE TITLE
Key Error in Python Splunk SDK while accessing KV store

### ISSUE THREAD

**Issue by souravsharma6633** [splunk/splunk-sdk-python#498] opened 2022-11-18 12:31 UTC
Hi,
I am facing the same **KeyError** issue as referenced here **https://github.com/splunk/splunk-sdk-python/issues/256** . 
But, I already have the collection defined in collections.conf file. I am **able to CRUD** the collection from the rest **API** but custom command is giving this KeyError.
Urgent help is needed.

Thanks,
Sourav

**Comment by souravsharma6633** [comment] 2022-11-18 12:42
On my local, when I am the admin it's working fine. But, on company hosted splunk, it is throwing the error.

**Comment by akaila-splunk** [comment] 2022-11-29 12:35
Hi @souravsharma6633 , Would you please share the steps to reproduce the issue. Based on our initial analysis it seems like an access issue, so if you share the your use case we may be able to identify the root cause.

**Comment by souravsharma6633** [comment] 2022-12-01 06:41
Hi @akaila-splunk, I am having a KVStore and lookup defined in collections.conf/transfomrms.conf. What I debugged till now is when I am trying to access KVStore using client.connect function of splunklib, it is being called once by the stream function. I am using the StreamingCommand to stream, process and yield the data.
But, the internal logs show that the storage/collections/config is being called on the search head I am connecting to ..and all the indexers. The search head is giving a 200 response while the indexers are giving 404 error. I am getting KeyError as if my collection in KVStore does not exist.
I have tried using local=true in commands.conf also for my custom command. But, still same behavior.
FYI, inputlookup/outputlookup commands work fine with all the requests going to SH only. API is also working fine.

Now, I need inputs on what can be the issue? Need some fast response as the issue is being persistent for 2 weeks and I am not able to proceed.

Thanks and Regards,
Sourav

**Comment by akaila-splunk** [comment] 2022-12-05 12:36
Hi @souravsharma6633, we have tried to access the kvstore from the CSC app with the code mentioned in issue#256 but unable to reproduce issue on our end, we are getting the data without any errors. so requesting you to share the .py script file code along with .conf files and spl query, and information about the environment along with version details, will help us to reproduce the issue.

**Comment by akaila-splunk** [comment] 2023-01-11 07:09
Closing the Issue as we haven't received any response. @souravsharma6633  please reopen the Issue if you still face the issue.

**Closed by akaila-splunk** 2023-01-11 07:09 UTC
